### ISSUE TITLE
Hooks

### ISSUE THREAD

**Issue by CarsonF** [samuelcastro/react-splitio#1]
Hey I'm looking to get some of my SplitIO boilerplate out of my app. I also wrote a wrapper for Split it's just a little different. I'm hoping we can work together to improve this library.

Here's my code, it's only ~100 lines. I can PR too, but didn't want to put in the effort prematurely.
```tsx
import { SplitFactory } from '@splitsoftware/splitio';
import {
  Attributes,
  IBrowserSettings,
  IClient,
  TreatmentWithConfig,
} from '@splitsoftware/splitio/types/splitio';
import * as React from 'react';
import {
  createContext,
  FunctionComponent,
  useContext,
  useEffect,
  useState,
} from 'react';

export const SplitProvider: FunctionComponent<IBrowserSettings> = ({
  children,
  ...settings
}) => {
  const {
    startup = {},
    scheduler = {},
    core,
    features = {},
    storage = {},
    debug,
    impressionListener,
  } = settings;
  const clientDeps = [
    startup.readyTimeout,
    startup.requestTimeoutBeforeReady,
    startup.retriesOnFailureBeforeReady,
    startup.eventsFirstPushWindow,
    scheduler.featuresRefreshRate,
    scheduler.impressionsRefreshRate,
    scheduler.metricsRefreshRate,
    scheduler.segmentsRefreshRate,
    scheduler.eventsPushRate,
    scheduler.eventsQueueSize,
    scheduler.offlineRefreshRate,
    core.authorizationKey,
    core.key,
    core.trafficType,
    core.labelsEnabled,
    ...Object.entries(features).map((k, v) => `${k}::${v}`),
    storage.type,
    storage.prefix,
    debug,
    impressionListener,
  ];

  const [client, setClient] = useState<IClient | null>(null);
  const [ready, setReady] = useState(false);
  const [updated, setUpdated] = useState(0);

  useEffect(() => {
    const nextClient = SplitFactory(settings).client();
    setClient(nextClient);
    nextClient.on(nextClient.Event.SDK_READY, () => {
      setReady(true);
      setUpdated(Date.now());
    });
    nextClient.on(nextClient.Event.SDK_UPDATE, () => {
      setUpdated(Date.now());
    });

    return () => {
      if (client) {
        client.destroy();
      }
      setReady(false);
      setUpdated(0);
    };
  }, clientDeps);

  return (
    <SplitContext.Provider value={{ client: ready ? client : null, updated }}>
      {children}
    </SplitContext.Provider>
  );
};

const SplitContext = createContext({
  client: null as IClient | null,
  updated: 0,
});

const defaultTreatment: TreatmentWithConfig = {
  treatment: 'control', // SplitIO's default value is "control"
  config: null,
};
export const useSplitTreatment = (
  splitName: string,
  attributes?: Attributes
): TreatmentWithConfig => {
  const { client, updated } = useContext(SplitContext);
  const [treatment, setTreatment] = useState(defaultTreatment);
  useEffect(() => {
    const next = client
      ? client.getTreatmentWithConfig(splitName, attributes)
      : defaultTreatment;
    setTreatment(next);
  }, [client, updated]);
  return treatment;
};

export const useSplitTrack: () => IClient['track'] = () => {
  const { client } = useContext(SplitContext);
  return client ? client.track : () => false;
};
```
Usage: 
```ts
const { treatment, config } = useSplitTreatment('MY_SPLIT');
if (treatment === 'on') {
  // do thing
}

const track = useSplitTrack();
const handleClick = () => {
  track('button_clicked', ...);
};
```

Besides the hooks, the biggest difference is my client is re-created when any of the config changes. Unfortunately, we have to check all the config properties to do so. My use case is when ever a user logs in I set their user ID as the `core.key` property.

**Comment by samuelcastro** [comment]
Hey @CarsonF really nice work, of course we can work together, to include hooks is one of my TODOS on this project. 

As far as I could see also in terms of difference between the library and your code is that I wanted to create something reusable to be consumed through simple react components like:

```
<Split name={['feature1', 'feature2']}>
// usage
</Split>
```

What's your thoughts and ideas to make this library better? Perhaps we should include your solution as well to give a different option, as a hook effect.

Thanks.

**Comment by CarsonF** [comment]
Yeah I have a `Split` component too, and actually another hook as well. Mine are a little more specific in treating the treatment as a boolean. I didn't want to include that as they might only fit my use case.
```ts
export const useSplit = (toggle: string, trueVal = 'on') => {
  const { treatment } = useSplitTreatment(toggle);
  return treatment === trueVal;
};

export interface SplitProps {
  toggle: string;
  /** Defaults to 'on' */
  trueVal?: string;
  /**
   * The node to render if toggle equals true value,
   * children can also be used instead of this prop.
   */
  then?: ReactNode;
  /**
   * The node to render if toggle does not equals true value.
   */
  else?: ReactNode;
}
export const Split: FunctionComponent<SplitProps> = props => {
  const split = useSplit(props.toggle, props.trueVal || 'on');
  return split
    ? ((props.then || props.children) as ReactElement) || null
    : (props.else as ReactElement) || null;
};
```

So I'm not suggesting getting rid of the `Split` HOC, it just becomes really trivial if it's fronting a hook. IMO there's no reason for the HOC now that we have hooks, but that's just my two cents 😉.

The reason I kept mine is it is rendering the children, not calling a function.
```tsx
<Split toggle="feature1">
  <MyFeature />
</Split>
```
vs:
```tsx
<Split name="feature1">
  {({ treatment }) =>
    treatment === 'on' ? <MyFeature /> : null
  }}
</Split>
```

---- 

From what I am seeing, everyone is rewriting their libraries to use hooks, and then updating their existing HOC components to use these hooks. That way users have both options.

**Comment by samuelcastro** [comment]
Got it, it's not an HOC though, it's render props, but I like your suggestion, as I mention this was on my [TODOS](https://github.com/samuelcastro/react-splitio#todo). Feel free to send a PR. I started the hook already but didn't have time to finish it up.

Also the reason why yours is just rendering the children rather than a function is that you're always assuming the treatment will be a boolean, the reason I render a children function is to give users the ability to do whatever they want with the treatment results, we can't assume it'll always be boolean.

Thanks Carson.

**Comment by CarsonF** [comment]
Cool.

> Also the reason why yours is just rendering the children rather than a function is that you're always assuming the treatment will be a boolean, the reason I render a children function is to give users the ability to do whatever they want with the treatment results.

Definitely, that's why I didn't bring it up at first.

---

I've never written/deployed a typescript library. Is there a reason all the types are defined separately? It seems like there's a lot there and a lot of types could just be inferred.

My context is also a little different. I allow the client to be null and then use that for both if the provider was not specified or if the client is not ready. Thoughts on that?

Thoughts on checking all of the config options and re-creating the client if they change?

**Comment by samuelcastro** [comment]
> I've never written/deployed a typescript library. Is there a reason all the types are defined separately? It seems like there's a lot there and a lot of types could just be inferred.

True, it's more to keep a good documentation and for organizational purposes.

> My context is also a little different. I allow the client to be null and then use that for both if the provider was not specified or if the client is not ready. Thoughts on that?

Why allow it to be null? My client is always created, what controls whether or not it's ready is a conditional variable `isReady` that's checked after `SDK_READY `, my treatments results might be either null or the value, this way the app does not block until the SDK is ready. Does that make sense?

> Thoughts on checking all of the config options and re-creating the client if they change?

In my case If config changes, the Provider component will re-render and the client will be created anyway, are you doing it differently?

Sorry if I misunderstood some of your questions.

**Comment by CarsonF** [comment]
> Why allow it to be null? My client is always created, what controls whether or not it's ready is a conditional variable `isReady` that's checked after `SDK_READY `, my treatments results might be either null or the value, this way the app does not block until the SDK is ready. Does that make sense?

`client.getTreatmentWithConfig()` will throw an error if the Provider isn't up the tree, because the default value is `{}`. So I check for that, and since whether the client is ready or not is basically the same logic I just combined them. "if client and ready return treatment else return default". The hooks/split components still hide the fact that the client is not defined or not ready, and don't block rendering.

> In my case If config changes, the Provider component will re-render and the client will be created anyway, are you doing it differently?

Your client is created in the constructor with the initial config value, it is never recreated.
My `useEffect` in `SplitProvider` re-creates the client based on `clientDeps` which is a list of the config values.

We are pretty close, I'm just trying to get your thought process.
I'll create a couple PRs and we can discuss there 😄

**Comment by samuelcastro** [comment]
> Your client is created in the constructor with the initial config value, it is never recreated.
My useEffect in SplitProvider re-creates the client based on clientDeps which is a list of the config values.

It's recreated when the whole component is re-render (including the constructor) when the parent component that injected the props changes.

Sure, PRs will be much appreciated, I need to create unit tests as well and a more automate releasing workflow.

**Comment by CarsonF** [comment]
> It's recreated when the whole component is re-render (including the constructor) when the parent component that injected the props changes.

It's recreated when the component is unmounted and remounted, not re-renders. If the parent conditionally changes the config object, that won't remount the Provider it will only re-render it. Hence the point of the `componentDidUpdate` lifecycle.

Happy to run tests if you don't believe me 🔍 🤔

**Comment by samuelcastro** [comment]
> It's recreated when the component is unmounted and remounted, not re-renders. If the parent conditionally changes the config object, that won't remount the Provider it will only re-render it. Hence the point of the componentDidUpdate lifecycle.

Yeah, you're right, it'll just remount not re-render, fair point.

I'm going to review those PRs asap, kinda busy now, but I'm really glad to see it coming so fast, great job.

**Comment by CarsonF** [comment]
No stress. I'm moving on with my day too 🏃💨

**Comment by samuelcastro** [comment]
Hey @CarsonF PRs reviewed, sorry the delay. I'm going to close this issue since we're handling it already.
