### ISSUE TITLE
JSX.Element doesn't allow null

### ISSUE THREAD

**Issue by wawoon** [samuelcastro/react-splitio#11]
# Problem

PR #9, which I created, caused another TypeScript error.

```tsx
<Split name="feature1">
  {(value: TreatmentWithConfig) =>
    value.treatment === 'on' ? <div /> : null
  }
</Split>
```
The sample usecase doesn't work because JSX.Element doesn't allow `null` value.

# Cause

In #9, I replaced `React.ReactNode` with `JSX.Element`, but `JSX.Element` doesn't include `null`. React.ReactNode is much loose types, and it allows null value, but JSX.Element (which extends React.ReactElement) does not includes null.

# Reproduce

I tried to reproduce the typescript error by codesandbox, but I coudn't reproduce it on codesandbox.

So I created other repository to reproduce it.

https://github.com/wawoon/react-splitio-ts-error-reproduce/blob/master/src/App.tsx#L14

# What should be fixed

```
declare global {
    namespace JSX {
        // tslint:disable-next-line:no-empty-interface
        interface Element extends React.ReactElement<any, any> { }
```
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react/index.d.ts#L2811

For example, React.FC uses `ReactElement | null` as return value.

```
    type FC<P = {}> = FunctionComponent<P>;

    interface FunctionComponent<P = {}> {
        (props: PropsWithChildren<P>, context?: any): ReactElement | null;
        propTypes?: WeakValidationMap<P>;
        contextTypes?: ValidationMap<any>;
        defaultProps?: Partial<P>;
        displayName?: string;
    }
```
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react/index.d.ts#L499

I think changing `JSX.Element` in src/types.ts to `JSX.Element | null` will fix this issue, but I don't have enough confidence about this solution.

Can you give me some advise? @samuelcastro

**Comment by samuelcastro** [comment]
@wawoon Thanks for catching an bringing this up, `JSX.Element | null` is ok, could you create a PR?
