### ISSUE TITLE
adding Optional attributes causes infinite re-render

### ISSUE THREAD

**Issue by samuelseaton** [samuelcastro/react-splitio#17]
steps to reproduce

1. use the split hook without any optional parameters (ex. `const [feature] = useSplit('some-split-example');`

2. make sure that it renders fine and returns "on" or "off"

3. use the split hook and add an optional parameter (ex. `const [feature] = useSplit('some-split-example', {
        email: 'some-email@gmail.com'
    });`

4. note that it re-renders over and over until it crashes the application

**Comment by CarsonF** [comment]
Look at the configuration section in the readme

**Comment by samuelcastro** [comment]
@samuelseaton Have you found the problem?

**Comment by samuelcastro** [comment]
Closing this, no more feedback was provided.
